### ISSUE TITLE
OAuth2 don't work.

### ISSUE THREAD

**Issue by joomlacorner** [mautic/mautic-joomla#14]
when we used OAuth2 for integrate with Social Network. but Mautic plugin for joomla still used OAuth1.How we can used if we don't have options for OAuth version in Plugin?

**Comment by escopecz** [comment]
Hey, could you try this version?

https://github.com/escopecz/mautic-joomla/archive/master.zip

It supports OAuth2. Let us please know if it works for you. We'll release it as a new version then.

**Comment by joomlacorner** [comment]
I have tested lasted update version. Now it's OAuth2 is worked. but it's miss some new language variable.  
- PLG_MAUTIC_RESET_BTN
- PLG_MAUTIC_OAUTH_VERSION
- PLG_MAUTIC_OAUTH_VERSION_DESC
- PLG_MAUTIC_DEBUG_ON
- PLG_MAUTIC_DEBUG_ON_DESC
- PLG_MAUTIC_LOG_ON
- PLG_MAUTIC_LOG_ON_DESC
- PLG_MAUTIC_REAUTHORIZE_SUCCESS

**Comment by escopecz** [comment]
All needed language strings are in the code. Please, try to update it manually with this package: 

https://github.com/mautic/mautic-joomla/archive/master.zip

If it solves the language problem.

**Comment by gavinerickson** [comment]
![image](https://user-images.githubusercontent.com/789065/27299035-d79b4b86-5522-11e7-8129-1b0350f25b30.png)

**Comment by escopecz** [comment]
The error message actually explains the problem well. The redirect URI you added in the API credentials configuration does not match the one provided during the authentication which is taken from the website you authenticated from. Try to [follow the steps](https://github.com/mautic/mautic-joomla#plugin-authorization) closely.

**Comment by dongilbert** [comment]
Stale
