### ISSUE TITLE
Fatal error on authorize - Joomla 2.5

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-joomla#15]
Hi folks,

Installed this on a 2.5.x site which is in the process of being migrated, so no biggie as I'll be on 3.x soon, but when I tried to authorise following the instructions on the Github repo, I get the white screen of death and the following error:

Fatal error: Uncaught exception 'Mautic\Exception\IncorrectParametersReturnedException' with message 'Incorrect access token parameters returned: Array' in /plugins/system/mautic/lib/Mautic/Auth/OAuth.php:418 Stack trace: #0 /plugins/system/mautic/lib/Mautic/Auth/OAuth.php(326): Mautic\Auth\OAuth->requestToken() #1 /plugins/system/mautic/mautic.php(192): Mautic\Auth\OAuth->validateAccessToken() #2 /system/mautic/mautic.php(144): plgSystemMautic->authorize(false) #3 [internal function]: plgSystemMautic->onAfterRoute() #4 /libraries/joomla/event/event.php(71): call_user_func_array(Array, Array) #5 /libraries/joomla/event/dispatcher.php(161): JEvent->update(Array) #6 /libraries/joomla/application/application.php(642): JDispatcher->trigger('onAfterRoute', NULL) #7 /administrator/includes/application.php(106): JApp in /plugins/system/mautic/lib/Mautic/Auth/OAuth.php on line 418

**Comment by escopecz** [comment]
Hey, could you try this version?

https://github.com/escopecz/mautic-joomla/archive/master.zip

I'm not sure if it solves your error since I was not able to recreate it, but give it a try, please.

**Comment by dongilbert** [comment]
This error pops up when using OAuth1a. Swap to OAuth2 and it should be good.
