### ISSUE TITLE
JS error on form Joomla Mautic 1.1.1 

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic-joomla#19]
After upgrading to Mautic 1.1.1 i get a JS error on my Joomla website when submitting a form.
The form button is stuck on "Please wait..."

''''Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://mautic.soetkees.nl') does not match the recipient window's origin ('http://www.soetkees.nl').(anonymous function) @ submit?formId=2:4''''

There are no errors in the mautic log.

Not sure this error is due to the the plugin or mautic
https://github.com/mautic/mautic/issues/525

**Comment by escopecz** [comment]
Could you clear your browser cache? Or probably the cache should be refreshed right now. Do you still see the error?

**Comment by wderuijter** [comment]
Hi John, 

Thanks for your reply. This was fixed with version 1.1.2.
