### ISSUE TITLE
Outdated API library 

### ISSUE THREAD

**Issue by sasivarnakumar** [mautic/mautic-joomla#22]
Please update the API library inside this plugin. I had to waste 1 hour just to figure out why my filter is not working while getLists. Filter has been renamed to search it was fixed in mautic-api library it seems but the joomla plugin has an outdated library in it.

Thanks and great work team mautic and all its supporters.

**Comment by escopecz** [comment]
Would you mind send the PR with updated API library?

**Comment by dongilbert** [comment]
Stale
