### ISSUE TITLE
Issue with .net domains

### ISSUE THREAD

**Issue by spignataro** [mautic/mautic-joomla#23]
https://github.com/mautic/mautic-joomla/blob/master/mauticApiHelper.php#L62

https://github.com/mautic/mautic-joomla/blob/master/mautic.php#L94

The two lines trim the t off a .net domain. I deleted the \t and this resolved the issue. I would suggest updating this trim function.

**Comment by spignataro** [comment]
Actually just merge this fix: https://github.com/mautic/mautic-joomla/pull/20

**Comment by parthlawate** [comment]
Confirmed that this is a problem

**Comment by rvbgnu** [comment]
Hi,
I was struggling to have mautic working last July, using a mydomain.mautic.net (free hosted solution). I'm just getting back to try again.
I thought that the commit 071c34cc60761781266c8060d7e1652a1c10f9a8 by @dongilbert had it fixed.
The solution here #20 should have fix it. But there is a Merge conflict. I've tested with this additional change 
https://github.com/mautic/mautic-joomla/pull/20/commits/a36c0e1d48d73d22f86831afd3eaa84025bf574e#diff-40a446f875d69812b16c19049304dc21R62
and it is working!

**Comment by dongilbert** [comment]
This has been fixed.

**Comment by rvbgnu** [comment]
Thank you Don!
