### ISSUE TITLE
Integrating with other extensions?

### ISSUE THREAD

**Issue by DerekBuntin** [mautic/mautic-joomla#31]
Integrating the Mautic connection with other extensions should be a fairly simple process.

The documentation says you should include the following file:

`require_once __DIR__ . '/mauticApiHelper.php';`

This would assume that the mauticApiHelper.php resides inside the same plugin or extension folder, which it doesn't, so do we need to include it like so, this is wrapped inside a private method:

```
$file = JPATH_PLUGINS . '/system/mautic/mauticApiHelper.php';
$fileExists = JFile::exists($file);
if($fileExists)
   {
      require_once $file;
   }else{
      return false;
   }
```

Or is it the case that we must copy the mauticApiHelper.php file to the root of the extension we are using?

I've not yet tested this but will likely have the answer myself shortly.

**Comment by joomkit** [comment]
Hi Derek,
just completed a test joomla to mautic contact save and just required it direct;
 require_once 'plugins/system/mautic/mauticApiHelper.php';

I also had to update the plugin mautic API library from github

**Comment by DerekBuntin** [comment]
So we'll need to update the plugin for this to work?

Sorry I haven't yet tested this myself.

**Comment by joomkit** [comment]
Yes you will need to update the API Library in the plugin and pick up the pull requests here:
https://github.com/mautic/mautic-joomla/pull/21
[Tested on Oauth2 running under https]

**Comment by DerekBuntin** [comment]
Marvellous, I'll do that now and will be testing this tomorrow, thank!
